#!/bin/bash

export curDir=$PWD

# set up freesurfer subjects dir
export SUBJECTS_DIR_ORIG=${SUBJECTS_DIR} 
export SUBJECTS_DIR='/Volumes/Denali_4D2/kohler/fMRI_EXP/HandmovementLS/surfaces'
export DATA_DIR='/Volumes/Denali_4D2/kohler/fMRI_EXP/HandmovementLS/data'

export SUB_ID='LS'

# run freesurfer
cd ${DATA_DIR}
export anatData='anatomical.nii.gz'
recon-all -i ${anatData} -subjid ${SUB_ID}
recon-all -autorecon-all -subjid ${SUB_ID} -3T -cubic -motioncor-flirt

# reset freesurfer subjects dir
export SUBJECTS_DIR=${SUBJECTS_DIR_ORIG}

# return to original directory
cd $curDir